package rules

import (
	"fmt"
	"sort"
	"strings"
)

// PAC 生成（M1-W3）：把加速域名清单编译成 PAC 脚本，由 serve 在
// 主端口 GET /pac 托管（系统代理 AutoConfigURL 直接指向它）。
//
// 匹配语义与 Matcher 对齐：精确域名 + 通配子域（shExpMatch 原生
// 支持两种），loopback 一律 DIRECT（本机服务不绕代理）。
func (m *Matcher) PAC(proxyAddr string) string {
	var b strings.Builder
	b.WriteString("// GHydra PAC — generated by ghydra serve, do not edit.\n")
	b.WriteString("// 加速域名走本地代理，其余全部 DIRECT（零打扰）。\n")
	b.WriteString("function FindProxyForURL(url, host) {\n")
	b.WriteString("  host = String(host).toLowerCase();\n")
	b.WriteString("  if (host == \"localhost\" || host == \"localhost.localdomain\" || host == \"::1\" || host == \"[::1]\" || isInNet(host, \"127.0.0.0\", \"255.0.0.0\")) return \"DIRECT\";\n")

	doms := append([]string(nil), m.doms...)
	sort.Strings(doms)
	if len(doms) > 0 {
		b.WriteString("  if (\n")
		for i, d := range doms {
			sep := " ||"
			if i == len(doms)-1 {
				sep = ""
			}
			fmt.Fprintf(&b, "    shExpMatch(host, %q)%s\n", d, sep)
		}
		fmt.Fprintf(&b, "  ) return \"PROXY %s\";\n", proxyAddr)
	}
	b.WriteString("  return \"DIRECT\";\n")
	b.WriteString("}\n")
	return b.String()
}
